version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app


  app_client:
    build:
      context: .
      dockerfile: /app_client/Dockerfile
    ports:
      - "88:88"
    depends_on:
      - postgres
    networks:
      - app

  app_manager:
    build:
      context: .
      dockerfile: /app_manager/Dockerfile
    ports:
      - "87:87"
    depends_on:
      - postgres
    networks:
      - app


networks:
  app:
volumes:
  postgres_data: