version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_db/postgres_data:/var/lib/postgresql/data
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: 'password'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  app_client:
    build:
      context: ./app_client
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app_manager:
    build:
      context: ./app_manager
      dockerfile: Dockerfile
    volumes:
      - ./app_manager/app:/opt/app
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    networks:
      - app


networks:
  app:
volumes:
  postgres_data: